version: '2.4'
services:
  prometheus:
    image: "prom/prometheus:v2.12.0"
    container_name: prometheus
    restart: always
    mem_limit: 4G
    ports:
     - "9090:9090"
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
#     = '--web.external-url=http://35.189.243.40:9090/'
    volumes:
     - "./prometheus/:/etc/prometheus/"
     - "prometheus_data:/prometheus"
    networks:
     - "monitoring"
  grafana:
    image: "grafana/grafana:6.3.3"
    container_name: grafana
    restart: always
    mem_limit: 4G
    ports:
     - "3000:3000"
    volumes:
     - "grafana_data:/var/lib/grafana"
    networks:
     - monitoring
    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,novalabs-annotations-panel,vonage-status-panel,fetzerch-sunandmoon-datasource,natel-discrete-panel,natel-influx-admin-panel
     - GF_SECURITY_ADMIN_PASSWORD=admin
  alertmanager:
    image: "prom/alertmanager:v0.18.0"
    container_name: alertmanager
    restart: always
    mem_limit: 4G
    ports:
     - "9093:9093"
    command:
#     - "--web.external-url=http://35.189.243.40:9093/"
     - "--config.file=/etc/alertmanager/alertmanager.yml"
     - "--storage.path=/alertmanager"
    volumes:
     - "./alertmanager/:/etc/alertmanager/"
     - "alertmanager_data:/alertmanager"
    networks:
     - "monitoring"
volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
networks:
  monitoring:
